sed -i '/voice/d' *.txt
sed -i '/priv.igame/d' *.txt
sed -i '/logo/d' *.txt
sed -i '/bilibili.com/d' *.txt
sed -i '/music.126/d' *.txt
sed -i '/share.weiyun/d' *.txt
sed -i '/api.pr.weixin.qq.com/d' *.txt
sed -i '/down-update.qq.com/d' *.txt
sed -i '/mp.weixin.qq.com/d' *.txt
sed -i '/res.wx.qq.com/d' *.txt
sed -i '/iyuji.cn/d' *.txt
sed -i '/bmob.cn/d' *.txt
sed -i '/youtube/d' *.txt
sed -i '/youtube/d' *.txt
sed -i '/google/d' *.txt
sed -i '/google/d' *.txt
sed -i '/114.qq.com/d' *.txt
sed -i '/163.com/d' *.txt
sed -i '/.apple.com/d' *.txt
sed -i '/.amazon.com/d' *.txt
sed -i '/.gmail.com/d' *.txt
sed -i '/facebook.com/d' *.txt
sed -i '/.twitter.com/d' *.txt
sed -i '/telegram/d' *.txt
sed -i '/windows/d' *.txt
sed -i '/alipay.com/d' *.txt
sed -i '/taobao.com/d' *.txt
sed -i '/.baidu.com/d' *.txt
sed -i '/.bing.com/d' *.txt
sed -i '/.bilibili.com/d' *.txt
sed -i '/.douban.com/d' *.txt
sed -i '/iqiyi.com/d' *.txt
sed -i '/.jd.com/d' *.txt
sed -i '/.miui.com/d' *.txt
sed -i '/.mi.com/d' *.txt
sed -i '/.microsoft.com/d' *.txt
sed -i '/.miwifi.com/d' *.txt
sed -i '/.taobao.com/d' *.txt
sed -i '/.zhihu.com/d' *.txt
sed -i '/.xunlei.com/d' *.txt
sed -i '/fb.me/d' *.txt
sed -i '/adobe.com/d' *.txt

